# Descargas/restauraciones grandes desde la UI
client_max_body_size 0;

location / {
    proxy_pass https://192.168.0.166:8007;
    proxy_ssl_verify off;
    include /etc/nginx/conf.d/snippets/proxy-ws.conf;
}
