location = / {
    return 302 /cortexdev-lan-ca.crt;
}

location = /cortexdev-lan-ca.crt {
    alias /etc/nginx/certs/cortexdev.lan/ca.pem;
    default_type application/x-x509-ca-cert;
    add_header Content-Disposition 'attachment; filename="cortexdev-lan-ca.crt"';
}
